### PR TITLE
Add functionality for managing editor conflicts

### PR DESCRIPTION
**Pull request by LucianBuzzo**
We now Poll GitHub for changes, and sync when there is an update available.
The entries are synced, unless a user is editing them, in which case a 'diff'
display is shown, which displays the fields that have been changed.
The GitHub repo is polled immediately before saving to see if there has been
a new commit. If there has, then the save is aborted, and the user is asked to
ensure that they have resolved any conflicts.
To facilitate these changes a new field called PS_UUID is added to all document
fragments. This field helps manage diffs and ensure that we can keep track of
fragments as they update and sync. This field is not searchable and is not
displayed in the UI.

screen shot 2017-10-05 at 10 52 13

Connects to #149

change-type: minor

### CODE REVIEW

**Comment by lekkas** [comment]
@LucianBuzzo Correct me if I'm wrong, but this change will also prevent anyone from editing Pensieve documents directly on the git repo, because every change will have to be accompanied with an updated `PS_UUID` which is not trivial to calculate manually. Maybe I'm missing something here, what is the big picture and benefits behind using Github instead of a (schemaless?) DB for storage?  

As a sidenote, I think we should follow the `Fixes #149` instead of the `Connects to #149` issue linking convention in the Pensieve repo, because the former will automatically close the linked issue(s) on PR merge (which makes sense given that changes are immediately deployed). `Connects to` only creates a reference to the respective issue which will have to manually be closed after PR merge.

**Comment by LucianBuzzo** [comment]
@lekkas The `PS_UUID` will get auto-generated if it is missing when someone saves a document, so It won't prevent people from editing on the GH repo directly. The `PS_UUID` is a constant value for each entry and shouldn't ever change.

**Comment by LucianBuzzo** [comment]
Also, thanks for the `Fixes` tip! I didn't realise that :smile:

**Comment by lekkas** [comment]
@LucianBuzzo awesome, thank you

**Comment by alexandrosm** [comment]
@lucianbuzzo -- I am not sure I get the current flow, but I'm also
worried/concerned about the ps_uuid -- let's discuss next week when I'm
back in action?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by LucianBuzzo** [comment]
@alexandrosm sure thing

**Pull request merged**
