### PR TITLE
Remove fontawesome css from pensieve and get user's to load it as a dependency

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Connects to #59

change-type: minor

### CODE REVIEW

**Comment by craig-mulligan** [comment]
What was the reasoning here? Some people won't want icons?

**Comment by craig-mulligan** [comment]
I usually use https://github.com/gorangajic/react-icons, you can load single svgs, which makes things pretty light.

**Comment by LucianBuzzo** [comment]
@craig-mulligan some people might already have bundled font-awesome css, and additionally, it means we don't have to worry about having it compiled into our app css, we just declare it as a dependency in the README

**Comment by LucianBuzzo** [comment]
react-icons looks like a good fit here

**Comment by LucianBuzzo** [comment]
https://github.com/resin-io/pensieve/issues/65

**Pull request merged**
