### PR TITLE
Generate an automated commit message when saving a change

### PR DESCRIPTION
**Pull request by LucianBuzzo**
screen shot 2017-10-05 at 12 09 46

Connects to #136

change-type: minor

### CODE REVIEW

**Comment by lekkas** [comment]
@LucianBuzzo I love the direction this is going. 

Do you think we can follow a more aggressive saving approach here by removing the modal altogether and committing with the auto - generated message when clicking 'Save' ? That would reduce the number of steps by one, which is a huge gain. Data entry (either scratchpad or meeting notes) is a menial and boring task already, I believe that pensieve adoption really depends on these small, but important UI wins like this.

**Comment by LucianBuzzo** [comment]
@lekkas Can we compromise, and add a settings option that stops the modal from showing? I think there are still use cases where a hand written commit message is useful.

**Comment by lekkas** [comment]
> Can we compromise, and add a settings option that stops the modal from showing? I think there are still use cases where a hand written commit message is useful.

@LucianBuzzo I am using very specific premises to support my argument that the modal should be removed in any case, can you please address my main point and give me specific reasons why obstructing the save flow with an extra step is a good idea that we need to compromise on? Even if hand written commit messages were a configurable option in the theoretical use cases you mention, why does it have to be a modal and not an extra field?

Obligatory disclaimer, I cannot even center a div with CSS properly, so my feedback is purely on the usability side, which I'm motivated to help fixing, because when Pensieve gets there we're going to use it on a daily basis. If the changes I suggest require a hell lot more work to the point that it becomes a limiting factor, please do bring it up as a point to the discussion.

**Comment by LucianBuzzo** [comment]
@lekkas If you are using pensieve to manage specs, I think you would want commit messages. I've just re-read your comments and I think you're asking for something like this?
screen shot 2017-10-05 at 13 42 31

**Comment by lekkas** [comment]
@LucianBuzzo requiring a commit message means that someone will, as some point, review, or look back to these commit messages. For all specs, agenda items and scratchpad I doubt we will ever need to look back into meta-info other than the author and the fragments that he/she edited. 

Yeap, the attached screenshot is in the lines of what I had in mind, the modal was my main concern 👍

**Comment by LucianBuzzo** [comment]
@lekkas I've killed the commit message input box entirely, here is the new workflow:

commit

**Comment by lekkas** [comment]
Looks great @LucianBuzzo

**Pull request merged**
